### ISSUE TITLE
Screen cast Show error

### ISSUE THREAD

**Issue by AshishGarg1988** [codewithkael/FirebaseWebRTCVideoCall#1]
when i click on start screen share application crashes with error 

Caused by: java.lang.SecurityException: Media projections require a foreground service of type ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION
]

**Comment by codewithkael** [comment]
What is your android version ?

**Comment by AshishGarg1988** [comment]
in one device i use android 12 and in another i have android 10

**Comment by codewithkael** [comment]
do you get this error on both devices ?

**Comment by AshishGarg1988** [comment]
Yes

**Comment by codewithkael** [comment]
just go to your manifest.xml and switch this service : 
        <service android:name=".service.MainService"/>
to this one : 
 <service android:name=".service.MainService"
            android:foregroundServiceType="mediaProjection"/>

I just fixed this issue on new commit.

**Comment by codewithkael** [comment]
try to pull again, I just added a new commit and fixed this issue.

**Comment by AshishGarg1988** [comment]
Now it works fine 
thanks
