### ISSUE TITLE
Not Issue but new feature

### ISSUE THREAD

**Issue by AshishGarg1988** [codewithkael/FirebaseWebRTCVideoCall#2]
Hi,

Is it possible to see window of other person over screen sharing 
scenario:
A call B and then A share screen to B in this case B is not visible to A so is it possible to have window of B on A screen so that A can see B during screen Sharing 

Thanks

**Comment by codewithkael** [comment]
you are recording your entire screen, so if I Preview your camera inside my screen during the screen share, it means I'm sending your camera back to yourself again, that is just a bad idea.
but if you wanna do it anyways, inside your webrtc client and inside startScreenCapturing function, comment the localScreenTrack.addSink() line.

**Comment by codewithkael** [comment]
if you start screen sharing, you still see the other peer's stream, i think you are making mistake

**Comment by AshishGarg1988** [comment]
But its not visible 
what i mean is if A start sharing screen then he is not able to see B's camera stream

**Comment by codewithkael** [comment]
you're still wrong.
the only thing is if a starts casting screen, he wont be able to see his own camera,
and b wont be able to see a's camera, since b is watching a's screen.

**Comment by AshishGarg1988** [comment]
yess but can't we still send camera feed to peer during during screen sharing for example can we maintain activity in pip mode with peers camera feed ??

**Comment by codewithkael** [comment]
Oh i get it now, let me think about it and implement it later. It is possible for sure but I have to find best practice.

**Comment by AshishGarg1988** [comment]
okay i am also searching for this if found anything let you know 

but its very good feature as live case scenario :  if A show something to B via phone then both can see face of each other to see actual face reactions

Thanks
