### ISSUE TITLE
Multiple devices connection

### ISSUE THREAD

**Issue by sceddd** [codewithkael/FirebaseWebRTCVideoCall#3]
Hello sir, is there anyway to allow user to connect with multiple users at the same time, like a streaming app.

**Comment by codewithkael** [comment]
hello, yes you can create an application like group call using webrtc.
but its not like i can explain in text, i should mentor you to do this.
if you are interested message me on telegram @codewithkael

**Comment by sceddd** [comment]
Is that too different with this one, I figured out I need to handle multiple devices with the onIceCandidate() method to handle multiple device coming from the IceServer.

**Comment by sceddd** [comment]
Hello sir, do I have to use NodeJS to build SFU broadcasts for send and receive from the server to handle this task? I'm stuck at this point. Is there any way that I can do it on Android ?

**Comment by codewithkael** [comment]
i dont understand what you need honestly, and i dont have enough free time to look each problem in details, hope you understand dude
